parameters:
    pim_magento_connector.normalizer.value.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\ProductValueNormalizer
    pim_magento_connector.normalizer.family.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\FamilyNormalizer

services:
    pim_magento_connector.normalizer.value:
        class: %pim_magento_connector.normalizer.value.class%

    pim_magento_connector.normalizer.family:
        class: %pim_magento_connector.normalizer.family.class%
